spring.application.name=spring-security
spring.datasource.url=jdbc:h2:mem:chubbdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.show-sql=true

# JWT Specific

jwt.secret=tixfxzqveErbSFN9LASaJgXLegCcvdZPe62h9QCUDKy

jwt.expiration=360000
